config/routes.rb
Rails.application.routes.draw do
  resources :sizes
  resources :measurements
  resources :patterns
  resources :variants

end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  has_many :variants

  def self.TYPES
    [
      'accessory',
      'dress',
      "men's",
      'pants/shorts',
      'skirt',
      'home',
      'swimwear',
      'tops',
      'undergarments',
      'outerwear'
    ]
  end

  def is_garment?
    ['dress', "men's", 'pants/shorts', 'skirt', 'swimwear', 'tops', 'undergarments', 'outerwear'].include?(category)
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]

  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all.order(:name)
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render :show, status: :created, location: @pattern }
      else
        format.html { render :new }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: 'Pattern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:name, :digital, :cut, :category, :notions, :fabrics)
    end
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
  <% if @pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

      <ul>
      <% @pattern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Pattern Information</h3>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'u-full-width' %>
    </div>
  </div>
  <div class="row">
    <div class="eight columns">
      <%= f.label :fabrics %>
      <%= f.text_field :fabrics, class: 'u-full-width' %>
    </div>
    <div class="four columns">
      <%= f.label :notions %>
      <%= f.text_field :notions, class: 'u-full-width' %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Inventory</h3>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <%= f.label :digital %>
      <%= f.check_box :digital %>
    </div>

    <div class="six columns">
      <%= f.label :cut %>
      <%= f.check_box :cut %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Category</h3>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= f.select :category, Pattern.TYPES.sort.collect { |p| [ p, p ] }, {prompt: true}, {class: 'u-full-width'} %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Boom!</h3>
    </div>
  </div>
  <%= f.submit 'Submit pattern', class: 'button-primary u-full-width' %>
<% end %>

app/views/patterns/edit.html.erb
<h2>Editing <%= @pattern.name %></h2>

<%= render 'form' %>

app/views/patterns/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Pattern Library</h2>

<table class="u-full-width">
  <thead>
    <tr>
      <th colspan='1'><i class="fa fa-scissors"></i></th>
      <th colspan='1'><i class="fa fa-files-o"></i></th>
      <th>Name</th>
      <th>Category</th>
      <th>Variants</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @patterns.each do |pattern| %>
      <tr>
        <td>
          <% if pattern.cut %>
            <i class="fa fa-check-circle"></i>
          <% else %>
            <i class="fa fa-circle-o"></i>
          <% end %>
        </td>
        <td>
          <% if pattern.digital %>
            <i class="fa fa-check-circle"></i>
          <% else %>
            <i class="fa fa-circle-o"></i>
          <% end %>
        </td>
        <td>
          <%= link_to pattern.name, pattern %>
        </td>
        <td><%= pattern.category %></td>
        <td><%= pattern.variants.count %></td>
        <td>
          <%= link_to pattern do %>
            <i class="fa fa-external-link"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_pattern_path(pattern) do %>
            <i class="fa fa-pencil"></i>
          <% end %>
        </td>
        <td>
          <%= link_to pattern, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/patterns/new.html.erb
<h2>New Pattern</h2>

<%= render 'form' %>

app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @pattern.name %>
  <div class="u-pull-right icon-list">
    <em>
      <%= @pattern.category %>
    </em>
    <% if @pattern.digital %>
      <i class="fa fa-files-o"></i>
    <% end %>
    <% if @pattern.cut %>
      <i class="fa fa-scissors"></i>
    <% end %>
    <%= link_to edit_pattern_path(@pattern) do %>
      <i class="fa fa-pencil"></i>
    <% end %>
  </div>
</h2>

<% if @pattern.fabrics %>
  <div class="divider">
    <h3>Fabrics</h3>
    <p><%= @pattern.fabrics %></p>
  </div>
<% end %> 

<% if @pattern.notions %>
  <div class="divider">
    <h3>Notions</h3>
    <p><%= @pattern.notions %></p>
  </div>
<% end %>

<% if @pattern.variants %> 
<div class="divider">
  
  <h3>Variants</h3>
  <% @pattern.variants.order(:label).each do |variant| %>

  <div class="clear-divider">
    <h4>
      <%= variant.label %>
      <div class="u-pull-right">
        <% if variant.measurement %>
          <%= link_to variant.measurement.name, variant.measurement, class: 'button' %>
        <% end %>
        <% if variant.size %>
          <%= link_to variant.size.name, variant.size, class: 'button' %>
        <% end %>
      </div>
    </h4>

      
    <table class="u-full-width">
      <thead>
        <tr>
          <th>44"</th>
          <% if variant.yardage_54 && variant.yardage_54 > 0 %>
            <th>54"</th>
          <% else %>
            <th colspan="1"></th>
          <% end %>
          <% if variant.yardage_60 && variant.yardage_60 > 0 %>
            <th>60"</th>
          <% else %>
            <th colspan="1"></th>
          <% end %>
          <% if @pattern.is_garment? %>
            <th>Bust</th>
            <th>Waist</th>
            <th>Hips</th>
          <% end %>
          <th colspan="2">Actions</th>
        </tr>
      </thead>

        <tbody>
          <tr>
            <td><%= pretty(variant.yardage_44).html_safe %></td>
            <% if variant.yardage_54 && variant.yardage_54 > 0 %>
              <td><%= pretty(variant.yardage_54).html_safe %></td>
            <% else %>
              <td></td>
            <% end %>
            <% if variant.yardage_60 && variant.yardage_60 > 0 %>
              <td><%= pretty(variant.yardage_60).html_safe %></td>
            <% else %>
              <td></td>
            <% end %>
            <% if @pattern.is_garment? %>
              <td><%= pretty(variant.bust).html_safe %></td>
              <td><%= pretty(variant.waist).html_safe %></td>
              <td><%= pretty(variant.hips).html_safe %></td>
            <% end %>
            <td>
              <%= link_to edit_variant_path(variant) do %>
                <i class="fa fa-pencil"></i>
              <% end %>
            </td>
            <td>
              <%= link_to variant, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </td>
          </tr>
          <% if variant.measurement %>
            <tr>
              <td></td>
              <td></td>
              <td><strong class="u-pull-right">Measurement</strong></td>
              <td><%= pretty(variant.measurement.bust).html_safe %></td>
              <td><%= pretty(variant.measurement.waist).html_safe %></td>
              <td><%= pretty(variant.measurement.hips).html_safe %></td>
              <td colspan="2">
                <%= link_to variant.measurement do %>
                  <i class="fa fa-external-link"></i>
                <% end %>
              </td>
            </tr>
          <% end %>

          <% if variant.size %>
            <tr>
              <td></td>
              <td></td>
              <td><strong class="u-pull-right">Size</strong></td>
              <td><%= pretty(variant.size.bust).html_safe %></td>
              <td><%= pretty(variant.size.waist).html_safe %></td>
              <td><%= pretty(variant.size.hips).html_safe %></td>
              <td colspan="2">
                <%= link_to variant.size do %>
                  <i class="fa fa-external-link"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
<% end %>
</div>