config/routes.rb
Rails.application.routes.draw do
  resources :sizes
  resources :measurements
  resources :patterns
  resources :variants

end

app/models/variant.rb
class Variant < ActiveRecord::Base
  belongs_to :pattern
  belongs_to :measurement
  belongs_to :size

  after_save :process_size

  private 
  def process_size
    return if @inside_callback
    @inside_callback = true
    if self.size
      self.update_attributes({
        bust: size.bust,
        waist: size.waist,
        hips: size.hips
      })
    end
  end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_variant, only: [:show, :edit, :update, :destroy]

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @variant = Variant.new
  end

  # GET /variants/1/edit
  def edit
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to @variant.pattern, notice: 'Variant was successfully created.' }
        format.json { render :show, status: :created, location: @variant }
      else
        format.html { render :new }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to @variant.pattern, notice: 'Variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant }
      else
        format.html { render :edit }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant.destroy
    respond_to do |format|
      format.html { redirect_to variants_url, notice: 'Variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant
      @variant = Variant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.require(:variant).permit(:label, :pattern_id, :yardage_44, :yardage_54, :yardage_60, :bust, :waist, :hips, :measurement_id, :size_id)
    end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/variants/_form.html.erb
<%= form_for(@variant) do |f| %>
  <div class="row">
    <div class="twelve columns">
      <% if @variant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@variant.errors.count, "error") %> prohibited this variant from being saved:</h2>

          <ul>
          <% @variant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div class="twelve columns divider">
      <h3>Pattern Information</h3>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= f.label :label, 'Variant & size label' %>
      <%= f.text_field :label, class: 'u-full-width' %>
    </div>

  <div class="row">
    <div class="six columns">
      <%= f.label :measurement_id %>
      <%= f.collection_select(:measurement_id, Measurement.all.order(:name), :id, :name, { prompt: true }, {class: 'u-full-width'}) %>
    </div>
    <div class="six columns">
      <%= f.label :pattern_id %>
      <%= f.collection_select(:pattern_id, Pattern.all.order(:name), :id, :name, { prompt: true }, {class: 'u-full-width'}) %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Yardage</h3>
      <p><em>Floats, please.</em></p>
    </div>
  </div>
  <div class="row">
    <div class="four columns">
      <%= f.label :yardage_44, '44" bolt' %>
      <%= f.number_field :yardage_44, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :yardage_54, '54" bolt' %>
      <%= f.number_field :yardage_54, class: 'u-full-width', step: 'any' %>    
    </div>
    <div class="four columns">
      <%= f.label :yardage_60, '60" bolt' %>
      <%= f.number_field :yardage_60, class: 'u-full-width', step: 'any' %>      
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Sizing Measurements</h3>
      <p><em>Floats or a preset size combo.</em></p>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= f.label :size_id %>
      <%= f.collection_select(:size_id, Size.all.order(:name), :id, :label, { prompt: true }, {class: 'u-full-width'}) %>
    </div>
  </div>
  <div class="row">
    <div class="four columns">
      <%= f.label :bust %>
      <%= f.number_field :bust, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :waist %>
      <%= f.number_field :waist, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :hips %>
      <%= f.number_field :hips, class: 'u-full-width', step: 'any' %>      
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Boom!</h3>
    </div>
  </div>
  <%= f.submit 'Submit variant', class: 'button-primary u-full-width' %>
<% end %>

app/views/variants/edit.html.erb
<h2>Editing Variant</h2>

<h3><%= @variant.label %></h3>

<%= render 'form' %>

app/views/variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Variants</h1>

<table>
  <thead>
    <tr>
      <th>Size</th>
      <th>Pattern</th>
      <th>44</th>
      <th>54</th>
      <th>60</th>
      <th>Bust</th>
      <th>Waist</th>
      <th>Hips</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variants.each do |variant| %>
      <tr>
        <td><%= variant.size %></td>
        <td><%= variant.pattern %></td>
        <td><%= variant.44 %></td>
        <td><%= variant.54 %></td>
        <td><%= variant.60 %></td>
        <td><%= variant.bust %></td>
        <td><%= variant.waist %></td>
        <td><%= variant.hips %></td>
        <td><%= link_to 'Show', variant %></td>
        <td><%= link_to 'Edit', edit_variant_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variant', new_variant_path %>

app/views/variants/new.html.erb
<h2>New Variant</h2>

<%= render 'form' %>

app/views/variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Size:</strong>
  <%= @variant.size %>
</p>

<p>
  <strong>Pattern:</strong>
  <%= @variant.pattern %>
</p>

<p>
  <strong>44:</strong>
  <%= @variant.yardage_44 %>
</p>

<p>
  <strong>54:</strong>
  <%= @variant.yardage_54 %>
</p>

<p>
  <strong>60:</strong>
  <%= @variant.yardage_60 %>
</p>

<p>
  <strong>Bust:</strong>
  <%= @variant.bust %>
</p>

<p>
  <strong>Waist:</strong>
  <%= @variant.waist %>
</p>

<p>
  <strong>Hips:</strong>
  <%= @variant.hips %>
</p>

<%= link_to 'Edit', edit_variant_path(@variant) %> |
<%= link_to 'Back', variants_path %>