config/routes.rb
Rails.application.routes.draw do
  resources :sizes
  resources :measurements
  resources :patterns
  resources :variants

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  has_many :variants
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]

  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:neck_to_waist, :nape_to_waist, :armpit_to_waist, :upper_back, :shoulder_rise, :waist, :bust, :hips, :name, :inseam)
    end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= form_for(@measurement) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Person</h3>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'u-full-width' %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Standard measurements</h3>
    </div>
  </div>
  <div class="row">
    <div class="four columns">
      <%= f.label :bust %>
      <%= f.number_field :bust, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :waist %>
      <%= f.number_field :waist, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :hips %>
      <%= f.number_field :hips, class: 'u-full-width', step: 'any' %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Additional measurements</h3>
    </div>
  </div>
  <div class="row">
    <div class="four columns">
      <%= f.label :inseam %>
      <%= f.number_field :inseam, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :upper_back %>
      <%= f.number_field :upper_back, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :shoulder_rise %>
      <%= f.number_field :shoulder_rise, class: 'u-full-width', step: 'any' %>
    </div>
  </div>
  <div class="row">
    <div class="four columns">
      <%= f.label :neck_to_waist %>
      <%= f.number_field :neck_to_waist, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :nape_to_waist %>
      <%= f.number_field :nape_to_waist, class: 'u-full-width', step: 'any' %>
    </div>
    <div class="four columns">
      <%= f.label :armpit_to_waist %>
      <%= f.number_field :armpit_to_waist, class: 'u-full-width', step: 'any' %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns divider">
      <h3>Boom!</h3>
    </div>
  </div>
  <%= f.submit 'Submit measurements', class: 'button-primary u-full-width' %>
<% end %>

app/views/measurements/edit.html.erb
<h2>Editing Measurement</h2>

<h3><%= @measurement.name %></h3>

<%= render 'form' %>

app/views/measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Measurements</h2>

<table class="u-full-width">
  <thead>
    <tr>
      <th>Name</th>
      <th>Bust</th>
      <th>Waist</th>
      <th>Hips</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measurements.each do |measurement| %>
      <tr>
        <td><%= link_to measurement.name, measurement %></td>
        <td><%= measurement.bust %></td>
        <td><%= measurement.waist %></td>
        <td><%= measurement.hips %></td>
        <td>
          <%= link_to measurement do %>
            <i class="fa fa-external-link"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_measurement_path(measurement) do %>
            <i class="fa fa-pencil"></i>
          <% end %>
        </td>
        <td>
          <%= link_to measurement, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/measurements/new.html.erb
<h2>New Measurement</h2>

<%= render 'form' %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @measurement.name %>
    <div class="u-pull-right icon-list">
      <%= link_to edit_measurement_path(@measurement) do %>
        <i class="fa fa-pencil"></i>
      <% end %>
  </div>
</h2>

<div class="divider">
  <h3>Measurements</h3>
</div>

<table class="u-full-width">
  <thead>
    <th>Bust</th>
    <th>Waist</th>
    <th>Hips</th>
    <% if @measurement.inseam && @measurement.inseam  > 0%> 
      <th>Inseam</th>
    <% end %>
    <% if @measurement.neck_to_waist && @measurement.neck_to_waist  > 0%> 
      <th>Neck to waist</th>
    <% end %>
    <% if @measurement.nape_to_waist && @measurement.nape_to_waist  > 0%> 
      <th>Nape to waist</th>
    <% end %>
    <% if @measurement.armpit_to_waist && @measurement.armpit_to_waist  > 0%> 
      <th>Armpit to waist</th>
    <% end %>
    <% if @measurement.upper_back && @measurement.upper_back  > 0%> 
      <th>Upper back</th>
    <% end %>
    <% if @measurement.shoulder_rise && @measurement.shoulder_rise  > 0%> 
      <th>Shoulder rise</th>
    <% end %>
  </thead>
  <tbody>
    <td><%= pretty(@measurement.bust).html_safe %></td>
    <td><%= pretty(@measurement.waist).html_safe %></td>
    <td><%= pretty(@measurement.hips).html_safe %></td>
    <% if @measurement.inseam && @measurement.inseam > 0 %>
      <td><%= pretty(@measurement.inseam).html_safe %></td>
    <% end %>
    <% if @measurement.neck_to_waist && @measurement.neck_to_waist > 0 %>
      <td><%= pretty(@measurement.neck_to_waist).html_safe %></td>
    <% end %>
    <% if @measurement.nape_to_waist && @measurement.nape_to_waist > 0 %>
      <td><%= pretty(@measurement.nape_to_waist).html_safe %></td>
    <% end %>
    <% if @measurement.armpit_to_waist && @measurement.armpit_to_waist > 0 %>
      <td><%= pretty(@measurement.armpit_to_waist).html_safe %></td>
    <% end %>
    <% if @measurement.upper_back && @measurement.upper_back > 0 %>
      <td><%= pretty(@measurement.upper_back).html_safe %></td>
    <% end %>
    <% if @measurement.shoulder_rise && @measurement.shoulder_rise > 0 %>
      <td><%= pretty(@measurement.shoulder_rise).html_safe %></td>
    <% end %>
  </tbody>
</table>