config/routes.rb
Rails.application.routes.draw do
  resources :sizes
  resources :measurements
  resources :patterns
  resources :variants

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stitchery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="twelve columns header">
        <h1>Stitchery Pattern Inventory</h1>
      </div>
    </div>
    <div class="row">
      <div class="two columns nav">
        <ul>
          <li>
            <strong>Patterns</strong>
          </li>
          <li>
            <%= link_to patterns_path do %>
              <i class="fa fa-book"></i> Library
            <% end %>
          </li>
          <li>
            <%= link_to new_pattern_path do %>
              <i class="fa fa-plus"></i> Add new pattern
            <% end %>
          </li>
          <li>
            <%= link_to new_variant_path do %>
              <i class="fa fa-plus"></i> Add new variant
            <% end %>
          </li>
        </ul>

        <ul>
          <li>
            <strong>Sizes</strong>
          </li>
          <li>
            <%= link_to sizes_path do %>
              <i class="fa fa-book"></i> Library
            <% end %>
          </li>
          <li>
            <%= link_to new_size_path do %>
              <i class="fa fa-plus"></i> Add new
            <% end %>
          </li>
        </ul>

        <ul>
          <li>
            <strong>Measurements</strong>
          </li>
          <li>
            <%= link_to measurements_path do %>
              <i class="fa fa-book"></i> Library
            <% end %>
          </li>
          <li>
            <%= link_to new_measurement_path do %>
              <i class="fa fa-plus"></i> Add new
            <% end %>
          </li>
        </ul>
      </div>
      <div class="ten columns">
        <%= yield %>
      </div>
    </div>
  </div>


</body>
</html>